XBE_TITLE = xblazyfoo_031_scrolling_backgrounds
GEN_XISO = $(XBE_TITLE).iso
SRCS = $(CURDIR)/main.c
NXDK_DIR ?= $(CURDIR)/../../.nxdk
NXDK_SDL = y
CFLAGS += -I$(CURDIR)/../common -DLAZYFOO_LESSON=31

include $(NXDK_DIR)/Makefile
