XBE_TITLE = xblazyfoo_014_animated_sprites_vsync
GEN_XISO = $(XBE_TITLE).iso
SRCS = $(CURDIR)/main.c
NXDK_DIR ?= $(CURDIR)/../../.nxdk
NXDK_SDL = y
CFLAGS += -I$(CURDIR)/../common -DLAZYFOO_LESSON=14

include $(NXDK_DIR)/Makefile
