XBE_TITLE = xblazyfoo_032_text_input_clipboard
GEN_XISO = $(XBE_TITLE).iso
SRCS = $(CURDIR)/main.c
NXDK_DIR ?= $(CURDIR)/../../.nxdk
NXDK_SDL = y
CFLAGS += -I$(CURDIR)/../common -DLAZYFOO_LESSON=32

include $(NXDK_DIR)/Makefile
